### ISSUE TITLE
Use the `metricsPath` and `metricsPort` from the clowder configuration

### ISSUE THREAD

**Issue by Sgitario** [RedHatInsights/clowder-quarkus-config-source#217]
Having the following clowder config file:

```json
{
"kafka": {
 "brokers": [
   {
     "hostname": "localhost",
     "port": 9092
   }
 ],
 "topics": []
},
"metricsPath": "/metrics",
"metricsPort": 9000,
"privatePort": 10000,
"publicPort": 8000,
"webPort": 8000
}
```

The Quarkus application should configure the management port with the metricsPort 8000 and the path /metrics in https://quarkus.io/guides/all-config#quarkus-micrometer_quarkus.micrometer.export.prometheus.path.

#### Acceptance Criteria
Allow getting the clowder values like `clowder.metricsPort`and `clowder.metricsPath`
Check whether there is a way to reduce the number of properties from:

```yaml
 management:
    port: ${METRICS_PORT}
    # App interface expects metrics to be served right off the root context
    root-path: /
    enabled: true
  micrometer:
    export:
      prometheus:
        path: ${METRICS_PATH}
      json:
        path: ${METRICS_PATH}
```
